#服务启动端口
server :  
  port :  8080
  servlet-path: /
spring:
  datasource:
    initialize: false
  redis:
    pool:
      max-active: 20
      max-idle: 10
      max-wait: 1000
      min-idle: 5
    database: 0
    cache:
      clusterNodes: 192.168.0.133:7001
      password: 123456
      commandTimeout: 5000
  http:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB
      file-size-threshold: 0
  thymeleaf:
    cache: false
    mode: HTML5
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: UTF-8
    prefix: classpath:/template/
    suffix: .html
logging:
  level: info
  
